version: '3.9'
services:
  postgresql: 
    image: postgres:latest
    restart: unless-stopped
    container_name: postgresql
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db:/var/lib/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db: